[package]
name = "zeek-xdp-loader-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
zeek-xdp-loader-common = { path = "../zeek-xdp-loader-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "zeek-xdp-loader"
path = "src/main.rs"
